### ISSUE TITLE
Please add a screen shot

### ISSUE THREAD

**Issue by unixorn** [hanbinpro/ysm-zsh-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots so that users can see what they look like without having to install them.

**Comment by hanbinpro** [comment]
OK. This theme is for my own use, it is relatively simple. But I think some people gonna like this simple style just like fish shell. @unixorn

**Comment by unixorn** [comment]
Thanks for adding the screen shot
